version: '3.2'
services:
  scala_dsp:
    container_name: scala_dsp
    build: DSP/.
    volumes:
      - ./DSP:/opt/DSP
    ports:
      - "8081:8081"
    tty: true
  scala_ssp:
    container_name: scala_ssp
    build: SSP/.
    volumes:
      - ./SSP:/opt/SSP
    ports:
      - "8082:8082"
    tty: true
